# QTrader Data Sources Configuration
#
# Maps logical data sources (used in Instrument) to physical adapters.
# Supports environment variable substitution using ${VAR_NAME} syntax.
#
# NAMING CONVENTION:
#   Source names should follow: <provider>-<region>-<asset>-<freq>[-variant]
#   Examples:
#     - algoseek-us-equity-1d-unadjusted
#     - binance-crypto-1m
#     - algoseek-us-futures-1d-unadjusted
#
# METADATA FIELDS (for DataSourceSelector matching):
#   - provider: Data provider name (algoseek, binance, etc.)
#   - asset_class: equity, futures, options, crypto, forex, fixed_income
#   - data_type: ohlcv, trades, quotes
#   - frequency: Use format like 1m, 5m, 15m, 1h, 1d (not "daily", "hourly")
#   - adapter: Adapter type (algoseekOHLC, etc.) - REQUIRED
#   - region: US, EU, ASIA, etc. (optional)
#   - adjusted: true/false - whether data is adjusted (optional, default false)
#   - timezone: IANA timezone like "America/New_York" (optional)
#   - price_currency: 3-letter currency code like "USD" (optional)
#   - price_scale: Number of decimal places for prices (optional)
#
# Configuration precedence:
#   1. Explicit path provided to DataSourceResolver
#   2. ./config/data_sources.yaml (project-relative)
#   3. ~/.qtrader/data_sources.yaml (user home)

data_sources:
  # Algoseek US Equity Daily Data (Unadjusted)
  algoseek-us-equity-1d-unadjusted:
    # Source metadata (for DataSourceSelector matching)
    provider: algoseek
    asset_class: equity
    data_type: ohlcv
    frequency: 1d
    region: US
    adjusted: false # this dataset provides unadjusted data
    timezone: America/New_York # NYSE/NASDAQ timezone
    price_currency: USD
    price_scale: 2 # 2 decimal places for USD

    # Adapter configuration
    adapter: algoseekOHLC
    root_path: "data/us-equity-daily-ohlc-standard-adjusted-secid-all-parquet-sample"
    mode: standard_adjusted
    path_template: "{root_path}/SecId={secid}/*.parquet"
    symbol_map: "data/equity_security_master_sample.csv"

    # Cache configuration (optional - enables incremental updates)
    cache_root: "data/cache/algoseek-us-equity-1d-unadjusted"
