# QTrader Data Sources Configuration
#
# Maps logical data sources (used in Instrument) to physical adapters.
# Supports environment variable substitution using ${VAR_NAME} syntax.
#
# NAMING CONVENTION:
#   Source names should follow: <provider>-<region>-<asset>-<freq>[-variant]
#   Examples:
#     - algoseek-us-equity-1d-unadjusted
#     - binance-crypto-1m
#     - algoseek-us-futures-1d-unadjusted
#
# METADATA FIELDS (for DataSourceSelector matching):
#   - provider: Data provider name (algoseek, binance, etc.)
#   - asset_class: equity, futures, options, crypto, forex, fixed_income
#   - data_type: ohlcv, trades, quotes, greeks, fundamentals
#   - frequency: Use format like 1m, 5m, 15m, 1h, 1d (not "daily", "hourly")
#   - region: US, EU, ASIA, etc. (optional)
#   - adjustment_mode: unadjusted, adjusted, split_adjusted (optional)
#
# Configuration precedence:
#   1. Explicit path provided to DataSourceResolver
#   2. ./config/data_sources.yaml (project-relative)
#   3. ~/.qtrader/data_sources.yaml (user home)

data_sources:
  # Algoseek US Equity Daily Data (Unadjusted)
  algoseek-us-equity-1d-unadjusted:
    # Source metadata (for DataSourceSelector matching)
    provider: algoseek
    asset_class: equity
    data_type: ohlcv
    frequency: 1d
    region: US
    adjustment_mode: unadjusted # Algoseek provides unadjusted data

    # Adapter configuration
    adapter: algoseekOHLC
    root_path: "data/us-equity-daily-ohlc-standard-adjusted-secid-all-parquet-sample"
    mode: standard_adjusted
    path_template: "{root_path}/SecId={secid}/*.parquet"
    symbol_map: "data/equity_security_master_sample.csv"
