# Test Run - Apple Stock 2019-2021
# Testing DataService with Algoseek data

# Backtest parameters
start_date: "2019-01-02"
end_date: "2021-12-31"
initial_equity: 100_000

# Replay speed for visualization (0.0 = full speed, 1.0 = 1 sec/bar)
replay_speed: 0.25

# Data configuration - per data source universe
data:
  sources:
    - name: "algoseek-us-equity-1d-unadjusted" # From data_sources.yaml
      universe: ["AAPL"] # Symbols to load from this source
    # Example: Multiple data sources
    # - name: "news-sentiment-feed"
    #   universe: ["AAPL"]  # News for AAPL only

# Strategies to run (referenced by name from registry)
strategies:
  - strategy_id: "buy_and_hold" # Registry name
    universe: ["AAPL"] # Symbols this strategy trades (subset of backtest universe)
    data_sources: ["algoseek-us-equity-1d-unadjusted"] # Data feeds this strategy uses
    configs: {} # Strategy-specific config overrides

risk_policy:
  name: "naive" # Registry name
  configs: {} #policy overrides
