# Multi-Strategy Tech vs ETF Backtest Configuration
#
# This demonstrates a multi-strategy backtest with:
# 1. SMA Crossover on tech stocks (60% allocation)
# 2. Buy & Hold on SPY ETF (40% allocation)
# 3. Performance-based reallocation every 90 days

name: "Multi-Strategy: Tech vs ETF"
description: "SMA Crossover on tech stocks vs Buy & Hold SPY with dynamic reallocation"

# Backtest time period (4 years)
start_date: "2020-01-01"
end_date: "2023-12-31"

# Portfolio settings
initial_capital: 200000.00

# Execution settings
execution:
  warmup: false
  warmup_bars: null
  slippage_model: "fixed"
  slippage_bps: 5.0
  commission_per_share: 0.01

# Global risk defaults
risk:
  default_position_size: 5000.00
  default_max_position_pct: 0.25
  default_allow_shorting: false

# Output settings
output:
  save_trades: true
  save_equity_curve: true
  generate_strategy_reports: true

# Strategy definitions
strategies:
  - name: "SMA_Tech"
    description: "SMA Crossover on 8 tech stocks"

    # Strategy implementation
    strategy_class: "examples.sma_crossover_strategy.SMACrossoverStrategy"

    # Strategy-specific parameters
    strategy_config:
      fast_period: 20
      slow_period: 50

    # Capital allocation (60% initial)
    initial_allocation_pct: 0.60

    # Tech stock universe
    instruments:
      - symbol: "AAPL"
        secid: 47896
      - symbol: "MSFT"
        secid: 59328
      - symbol: "GOOGL"
        secid: 98163
      - symbol: "NVDA"
        secid: 67461
      - symbol: "META"
        secid: 98426
      - symbol: "TSLA"
        secid: 72612
      - symbol: "AMD"
        secid: 2488
      - symbol: "INTC"
        secid: 44962

    # Per-strategy risk settings
    risk:
      position_size: 8000.00
      max_position_pct: 0.15
      allow_shorting: false
      max_positions: 5

    # Performance-based reallocation
    reallocation:
      policy: "performance_based"
      rebalance_frequency: "quarterly"
      lookback_period: 90
      min_allocation: 0.20
      max_allocation: 0.80
      metric: "sharpe_ratio"

  - name: "BuyHold_SPY"
    description: "Buy and Hold SPY ETF"

    # Strategy implementation
    strategy_class: "examples.buy_and_hold_strategy.BuyAndHoldStrategy"

    # No special config for buy & hold
    strategy_config: {}

    # Capital allocation (40% initial)
    initial_allocation_pct: 0.40

    # Single ETF universe
    instruments:
      - symbol: "SPY"
        secid: 78462

    # Per-strategy risk settings
    risk:
      position_size: null
      max_position_pct: 1.0
      allow_shorting: false
      max_positions: 1

    # Fixed allocation for conservative strategy
    reallocation:
      policy: "fixed"
